apiVersion: v1
kind: Service
metadata:
  name: task-manager-server
spec:
  type: NodePort
  selector:
    app: task-manager-server
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007